// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0h0VbwATiI1l_K1WBFUMP4BlEPbR5X_o',
    appId: '1:1020135674187:web:b5d14593da98ec81a218ce',
    messagingSenderId: '1020135674187',
    projectId: 'fleetlive-29705',
    authDomain: 'fleetlive-29705.firebaseapp.com',
    databaseURL: 'https://fleetlive-29705-default-rtdb.firebaseio.com',
    storageBucket: 'fleetlive-29705.firebasestorage.app',
    measurementId: 'G-PG1XS3B3EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdFGFYXiAcW5TPumto7hJJ3X3hNU0Ksc',
    appId: '1:1020135674187:android:9cdb4df0baf9ad78a218ce',
    messagingSenderId: '1020135674187',
    projectId: 'fleetlive-29705',
    databaseURL: 'https://fleetlive-29705-default-rtdb.firebaseio.com',
    storageBucket: 'fleetlive-29705.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbCTmYkLe0iMjvPwemk6FdP_Ah5Dvf6o',
    appId: '1:1020135674187:ios:f3ed1bd88bd9c746a218ce',
    messagingSenderId: '1020135674187',
    projectId: 'fleetlive-29705',
    databaseURL: 'https://fleetlive-29705-default-rtdb.firebaseio.com',
    storageBucket: 'fleetlive-29705.firebasestorage.app',
    iosClientId: '1020135674187-bgl5dnju0nqcv2uc126hplh0r5bdf2v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleetlive',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbbCTmYkLe0iMjvPwemk6FdP_Ah5Dvf6o',
    appId: '1:1020135674187:ios:f3ed1bd88bd9c746a218ce',
    messagingSenderId: '1020135674187',
    projectId: 'fleetlive-29705',
    databaseURL: 'https://fleetlive-29705-default-rtdb.firebaseio.com',
    storageBucket: 'fleetlive-29705.firebasestorage.app',
    iosClientId: '1020135674187-bgl5dnju0nqcv2uc126hplh0r5bdf2v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleetlive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0h0VbwATiI1l_K1WBFUMP4BlEPbR5X_o',
    appId: '1:1020135674187:web:127303a4b28c6301a218ce',
    messagingSenderId: '1020135674187',
    projectId: 'fleetlive-29705',
    authDomain: 'fleetlive-29705.firebaseapp.com',
    databaseURL: 'https://fleetlive-29705-default-rtdb.firebaseio.com',
    storageBucket: 'fleetlive-29705.firebasestorage.app',
    measurementId: 'G-FQ04YM7YPS',
  );
}
