import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../constants/app_colors.dart';
import '../../data/sample_data.dart';
class AddVehicleScreen extends StatefulWidget {
  const AddVehicleScreen({super.key});
  @override State<AddVehicleScreen> createState()=>_S();
}
class _S extends State<AddVehicleScreen> {
  final _fk=GlobalKey<FormState>();
  String _t='Car'; bool _dd=false;
  @override Widget build(BuildContext context){
    final dk=Theme.of(context).brightness==Brightness.dark;
    final bg=dk?AppColors.darkBg:AppColors.lightBg,card=dk?AppColors.darkCard:AppColors.lightCard,bdr=dk?AppColors.darkBorder:const Color(0xFFE2E8F0),tx=dk?Colors.white:const Color(0xFF0F172A),mt=dk?AppColors.white50:const Color(0xFF64748B),ibg=dk?AppColors.white10:const Color(0xFFF1F5F9);
    return Scaffold(backgroundColor:bg,body:SafeArea(child:Column(children:[
      Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:12),decoration:BoxDecoration(color:card,border:Border(bottom:BorderSide(color:bdr))),child:Row(children:[IconButton(onPressed:(){},icon:Icon(Icons.arrow_back_ios_new_rounded,color:mt,size:20),padding:EdgeInsets.zero),const SizedBox(width:8),Text('Add Vehicle',style:GoogleFonts.plusJakartaSans(fontSize:18,fontWeight:FontWeight.w700,color:tx))])),
      Expanded(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Form(key:_fk,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
        GestureDetector(onTap:(){},child:Container(height:160,width:double.infinity,decoration:BoxDecoration(color:ibg,borderRadius:BorderRadius.circular(20),border:Border.all(color:AppColors.primary.withValues(alpha:0.3),width:1.5)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Container(width:56,height:56,decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:0.15),borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.camera_alt_outlined,color:AppColors.primary,size:26)),const SizedBox(height:10),Text('Upload Vehicle Photo',style:GoogleFonts.plusJakartaSans(fontWeight:FontWeight.w700,fontSize:14,color:tx)),Text('JPEG, PNG up to 10 MB',style:GoogleFonts.plusJakartaSans(fontSize:11,color:mt)),const SizedBox(height:12),Row(mainAxisAlignment:MainAxisAlignment.center,children:[ElevatedButton(onPressed:(){},style:ElevatedButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:16,vertical:8),minimumSize:Size.zero),child:Text('Browse',style:GoogleFonts.plusJakartaSans(fontSize:12,fontWeight:FontWeight.w700))),const SizedBox(width:10),OutlinedButton(onPressed:(){},style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:16,vertical:8),minimumSize:Size.zero,side:BorderSide(color:bdr),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(10))),child:Text('Camera',style:GoogleFonts.plusJakartaSans(fontSize:12,fontWeight:FontWeight.w700,color:tx)))])]))),
        const SizedBox(height:20),
        _lbl('Vehicle Name',tx),
        TextFormField(style:GoogleFonts.plusJakartaSans(color:tx),decoration:_dec('e.g. Toyota Hilux',Icons.local_shipping_outlined,ibg,bdr,mt),validator:(v)=>v==null||v.isEmpty?'Required':null),
        const SizedBox(height:16),
        _lbl('Registration Number',tx),
        TextFormField(style:GoogleFonts.plusJakartaSans(color:tx,fontWeight:FontWeight.w700,letterSpacing:2),decoration:InputDecoration(hintText:'ABC-1234',hintStyle:GoogleFonts.plusJakartaSans(color:mt,letterSpacing:1),filled:true,fillColor:ibg,prefixIcon:Container(margin:const EdgeInsets.symmetric(horizontal:14,vertical:10),padding:const EdgeInsets.symmetric(horizontal:8),decoration:BoxDecoration(color:AppColors.white10,borderRadius:BorderRadius.circular(8)),child:Text('BD',style:GoogleFonts.plusJakartaSans(fontWeight:FontWeight.w800,fontSize:12,color:mt))),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide(color:bdr)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide(color:bdr)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:const BorderSide(color:AppColors.primary,width:1.5)),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:14)),validator:(v)=>v==null||v.isEmpty?'Required':null),
        const SizedBox(height:16),
        _lbl('Vehicle Type',tx),
        GestureDetector(onTap:()=>setState(()=>_dd=!_dd),child:Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:14),decoration:BoxDecoration(color:ibg,borderRadius:BorderRadius.circular(16),border:Border.all(color:_dd?AppColors.primary:bdr,width:_dd?1.5:1)),child:Row(children:[Icon(Icons.inventory_2_outlined,color:mt,size:20),const SizedBox(width:12),Expanded(child:Text(_t,style:GoogleFonts.plusJakartaSans(fontSize:14,color:tx))),AnimatedRotation(turns:_dd?0.5:0,duration:const Duration(milliseconds:200),child:Icon(Icons.keyboard_arrow_down_rounded,color:mt))]))),
        if(_dd)...[const SizedBox(height:6),Container(decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(16),border:Border.all(color:bdr),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:0.2),blurRadius:16,offset:const Offset(0,4))]),child:Column(children:vehicleTypes.asMap().entries.map((e){final sel=e.value==_t;return GestureDetector(onTap:()=>setState((){_t=e.value;_dd=false;}),child:Container(decoration:BoxDecoration(border:e.key<vehicleTypes.length-1?Border(bottom:BorderSide(color:bdr)):null),padding:const EdgeInsets.symmetric(horizontal:16,vertical:13),child:Row(children:[Expanded(child:Text(e.value,style:GoogleFonts.plusJakartaSans(fontSize:13,fontWeight:sel?FontWeight.w700:FontWeight.w400,color:sel?AppColors.primary:tx))),if(sel)const Icon(Icons.check_rounded,color:AppColors.primary,size:18)])));}).toList()))],
        const SizedBox(height:28),
        SizedBox(width:double.infinity,child:ElevatedButton(onPressed:(){if(_fk.currentState!.validate())ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Vehicle saved!',style:GoogleFonts.plusJakartaSans(fontWeight:FontWeight.w600)),backgroundColor:AppColors.success));},style:ElevatedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),child:Text('Save Vehicle',style:GoogleFonts.plusJakartaSans(fontSize:15,fontWeight:FontWeight.w800,color:Colors.white)))),
      ])))),
    ])));
  }
  Widget _lbl(String t,Color c)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Text(t,style:GoogleFonts.plusJakartaSans(fontSize:11,fontWeight:FontWeight.w700,color:c.withValues(alpha:0.7),letterSpacing:0.8)));
  InputDecoration _dec(String h,IconData i,Color bg,Color bdr,Color mt)=>InputDecoration(hintText:h,prefixIcon:Icon(i,size:20),filled:true,fillColor:bg,hintStyle:GoogleFonts.plusJakartaSans(color:mt,fontSize:14),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide(color:bdr)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide(color:bdr)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:const BorderSide(color:AppColors.primary,width:1.5)),errorBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:const BorderSide(color:AppColors.error)),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:14));
}
